config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "articles#index"

  resources :articles do
    resource :likes, only: [:show, :create, :destroy]
  end

  resources :searchs
  resources :books
  resources :searcheds, only: [:index]
  resources :timelines, only: [:index]

  resources :accounts, only: [:show] do
    resources :follows, only: [:show, :create]
    resources :unfollows, only: [:create]
  end

  resource :profile
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  extend OrderAsSpecified
  validates :title, presence: true
  validates :content, presence: true
  belongs_to :user
  has_many :likes, dependent: :destroy
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_one_attached :avatar
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :following, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :following_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :followings, through: :following_relationships, source: :following

  has_many :follower_relationships, foreign_key: 'following_id', class_name: 'Relationship', dependent: :destroy
  has_many :followers, through: :follower_relationships, source: :follower

  has_one :profile, dependent: :destroy

  def prepare_profile
    profile || build_profile
  end

  def avatar_image
    if profile&.avatar&.attached?
      profile.avatar
    else
      'default-avatar.png'
    end
  end

  def display_name
    profile&.nickname || self.email.split('@').first
  end

  def has_written?(article)
    articles.exists?(id: article.id)
  end

  def follow!(user)
    user_id = get_user_id(user)
    following_relationships.create!(following_id: user_id)
  end

  def unfollow!(user)
    user_id = get_user_id(user)

    relation = following_relationships.find_by!(following_id: user_id)
    relation.destroy!
  end

  def has_followed?(user)
    following_relationships.exists?(following_id: user.id)
  end

  def has_liked?(article)
    likes.exists?(article_id: article.id)
  end

  private
  def get_user_id(user)
    if user.is_a?(User)
      user.id
    else
      user
    end
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index 
    @articles = Article.paginate(page:params[:page]).order(created_at: :desc)

    article_like_count = Article.joins(:likes).group(:article_id).count
    article_liked_ids = Hash[article_like_count.sort_by{ |_, v| -v }].keys
    @article_ranking = Article.where(id: article_liked_ids).order_as_specified(id: article_liked_ids).limit(5)

    end 

  def new
    @article = current_user.articles.build
    @book_title = params[:book_title]
    @authors = params[:authors]
    @image_url = params[:image_url]
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
    @article = current_user.articles.find(params[:id])
    @book_title = params[:book_title]
    @authors = params[:authors]
    @image_url = params[:image_url]
  end

  def update
    @article = current_user.articles.find(params[:id])
    if @article.update(article_params)
      redirect_to article_path(@article), notice: '更新できました'
    else
      flash.now[:error] = '更新できませんでした'
      render :edit
    end
  end

  def destroy
    article = current_user.articles.find(params[:id])
    article.destroy!
    redirect_to root_path, notice: '削除しました'
  end

  private
  def article_params
    params.require(:article).permit(:title, :content, :book_title, :author, :image_url)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    def index
      search = params[:search]
      data = URI.encode"https://www.googleapis.com/books/v1/volumes?q=#{search}"
      uri = URI.parse(data)
      response = Net::HTTP.get(uri)
      res = JSON.parse(response)
      @r = res['items']
      
    end

    

    private
  end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :authenticate_user!
	
  def show
    user = User.find(params[:account_id])
    follow_status = current_user.has_followed?(user)
    render json: { hasFollowed: follow_status }
  end

	def create
		current_user.follow!(params[:account_id])
    redirect_to account_path(params[:account_id])
	end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	before_action :authenticate_user!

	def show
		article = Article.find(params[:article_id])
		like_status = current_user.has_liked?(article)
		render json: { hasLiked: like_status }
	end
	
	def create
		article = Article.find(params[:article_id])
		article.likes.create!(user_id: current_user.id)
		
		render json: { status: 'ok' }
	end

	def destroy
		article = Article.find(params[:article_id])
		like = article.likes.find_by!(user_id: current_user.id)
		like.destroy!
		render json: { status: 'ok' }
	end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @profile = current_user.profile
    @articles = current_user.articles.order(created_at: :desc)
  end

  def edit
    @profile = current_user.prepare_profile
  end

  def update
    @profile = current_user.prepare_profile
    @profile.assign_attributes(profile_params)

    if @profile.save
      redirect_to profile_path, notice: 'プロフィール更新'
    else
      render :edit
    end
  end

  private
  def profile_params
    params.require(:profile).permit(
      :nickname,
      :introduction,
      :avatar
    )
  end
end

app/controllers/searcheds_controller.rb
class SearchedsController < ApplicationController
  def index
    search = params[:search]
    @searched = Article.where(book_title: "#{search}")
    
  end
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  def index
  end

  def show
    
  end
end

app/controllers/timelines_controller.rb
class TimelinesController < ApplicationController
  def index
    user_ids = current_user.followings.pluck(:id)
    @articles = Article.where(user_id: user_ids).order(created_at: :desc)
  end
end

app/controllers/unfollows_controller.rb
class UnfollowsController < ApplicationController
  before_action :authenticate_user!

  def create
    current_user.unfollow!(params[:account_id])
    # render json: { status: 'ok' }
    redirect_to account_path(params[:account_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/show.html.haml
= render 'commons/profile', user: @user

app/views/articles/_form.html.haml
.container
  %ul
    - article.errors.full_messages.each do |message|
      %li= message
  = form_with(model: article, local: true) do |f|
    %div
      = f.label :title, 'タイトル'
    %div
      = f.text_field :title
    %div
      = f.label :content, '内容'
    %div
      = f.text_area :content
    %div
      = f.hidden_field :author, :value => @authors
    %div
      = f.hidden_field :book_title, :value => @book_title
    %div
      = f.hidden_field :image_url, :value => @image_url
    = f.submit '保存'

app/views/articles/edit.html.haml
= render 'form', article: @article

app/views/articles/index.html.haml
.articlesearch
  .search_text
    気になる本の記事を検索
  = form_tag(searcheds_path,:method => 'get') do
    = text_field_tag :search
    = submit_tag 'Search', :name => nil

%h3
  人気記事top5
.cards
  - @article_ranking.each do |rank|
    = link_to article_path(rank), class:'card' do
      .article_toppage
        .book_image
          = image_tag rank.image_url   
        .article_details     
          .article_title
            = rank.title
          .book_title
            = rank.book_title
          .author_name
            = rank.author
          .article_toppage_content
            = rank.content[0,50]
      .article_toppage_heart
        = image_tag 'heart.svg', class: 'iine-image'
        %span= rank.likes.count

= render 'commons/articles', articles: @articles


= link_to searchs_path do
  .float_btn
    %i.fa.fa-plus

app/views/articles/new.html.haml
= render 'form', article: @article, book_title: @book_title, author: @authors, image_url: @image_url

app/views/articles/show.html.haml
.article#article-show{data: {article_id: @article.id}}
  .detail_flex
    .article_detail_title
      = @article.title
    .detail_author_info
      = link_to account_path(@article.user) do
        = image_tag @article.user.avatar_image, class: 'icon_mini'
      = @article.user.profile&.nickname
  .article_content_wrapper
    .detail_book_image
      - if @article.image_url
        = image_tag @article.image_url
    .detail_bookinfo_flex
      .detail_book_title
        = @article.book_title
      .detail_book_author
        = @article.author
  .article_border
  .detail_article_content 
    = @article.content

  -@book_title = @article.book_title
  -@authors = @article.author
  -@image_url = @article.image_url

  - if user_signed_in?
    - if current_user.has_written?(@article)
      .article_btn
        = link_to edit_article_path(@article, :book_title => @book_title, :authors => @authors, :image_url => @image_url) do
          .edit_btn
            .edit_text
              Edit
        = link_to article_path(@article), data: {method: 'delete', confirm: '本当に削除してもよろしいですか'} do
          .delete_btn
            .delete_text
              Delete
    - else
      .heart_btn
        .heart.hidden.active-heart
          = image_tag 'heart-active.svg'
        .heart.hidden.inactive-heart
          = image_tag 'heart.svg'

app/views/books/index.html.haml
- if @r.nil?
  キーワードに合致する情報は見つかりませんでした
  よろしければ記事のタイトルに書名を入力してご利用いただければ幸いです
  = link_to '戻る', searchs_path
  = link_to '記事を書く', new_article_path
- else
  .searched_books
    - @r.each do |r|
      .searched_book
        - volumeInfo = r['volumeInfo']

        - links = volumeInfo['imageLinks']
        - if !links.nil?
          - @image_url = links['thumbnail']
          = image_tag @image_url
        - else
          画像がありません

        .searched_text
          - @book_title = volumeInfo['title']
          - if !@book_title.nil?
            = @book_title

          - @authors = volumeInfo['authors']
          - if !@authors.nil?
            - @authors.each do |author|
              = author
          
          = link_to '記事を書く', new_article_path(:book_title => @book_title, :authors => @authors, :image_url => @image_url), class: 'text-decoration new-article-link'

app/views/commons/_articles.html.haml
%h3 新着記事

.cards
  - articles.each do |article|
    = link_to article_path(article), class: 'card' do
      .article_toppage
        - if article.image_url
          .book_image
            = image_tag article.image_url
        .article_details
          .article_title
            = article.title
          .booktitle
            = article.book_title
          .author_name
            = article.author
          .article_toppage_content
            = article.content[0,50]
      .article_toppage_heart
        = image_tag 'heart.svg', class: 'iine-image'
        %span= article.likes.count

- if current_page?(articles_path)
  = will_paginate

app/views/commons/_profile.html.haml
.profile
  .profile_flex
    = image_tag user&.avatar_image, class: 'profile_icon'
    
    .profile_actionButton
      - if user == current_user 
        = link_to edit_profile_path do
          .edit_btn
            .edit_text 
              Edit 
      - else 
        - if current_user&.has_followed?(user)
          = link_to account_unfollows_path(user), data: {method: 'post'} do
            .edit_btn
              .edit_text
                Unfollow
        - else
          = link_to account_follows_path(user), data: {method: 'post'} do
            .edit_btn
              .edit_text
                follow

  .profile_info
    .profile_name
      #{user.display_name}
    .profile_introduction
      = user.profile&.introduction
  - if current_user == user
    .following_article
      = link_to 'フォローしたアカウントの記事一覧へ', timelines_path, class: 'text-decoration'  

.cards.profile_cards
  - user.articles.each do |a|
    = link_to article_path(a), class: 'card' do
      .article_toppage
        .book_image
          - if a.image_url
            = image_tag a.image_url
        .article_details
          .article_title
            = a.title
          .booktitle
            = a.book_title
          .author_name
            = a.author
          .article_toppage_content
            = a.content[0,100]
      .article_toppage_heart
        = image_tag 'heart.svg', class: 'iine-image'
        %span= a.likes.count

          
      
      

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Yomikata
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %link{:href => "https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css", :rel => "stylesheet"}/
  %body
    %header.header
      %p.header_pageTitle
        = link_to 'Yomikata', root_path, class: ' pageTitle'

      - if user_signed_in?
        - if !current_page?(profile_path)
          = link_to 'マイページ', profile_path, class: 'mypage'
      - else
        = link_to 'ログイン', new_user_session_path, class: 'mypage'
    %p.notice
      = notice
    %p.alert
      = alert
    .all_wrapper
      = yield

app/views/profiles/edit.html.haml
.container
  = form_with(model: @profile, url: profile_path, method: 'put', local: true) do |f|
    %div
      = f.label :avatar, 'アイコン'
    %div
      = f.file_field :avatar 
    %div 
      = f.label :nickname, '表示名'
    %div 
      = f.text_field :nickname, class: 'text'
    %div 
      = f.label :introduction, '自己紹介'
    %div 
      = f.text_area :introduction
    
    = f.submit '保存', class: 'btn-primary'

    

app/views/profiles/show.html.haml
= render 'commons/profile', user: current_user
= link_to 'ログアウト' , destroy_user_session_path, class: 'text-decoration profile_logout', data: { method: 'delete', confirm: 'ログアウトしてもよろしいですか'}

app/views/searcheds/index.html.haml
- if @searched == []
  お探しの本についての記事は見つかりませんでした
  = link_to '戻る', articles_path, class: 'text-decoration'
- else
  .cards
  - @searched.each do |article|
    = link_to article_path(article), class: 'card' do
      .article_toppage
        - if article.image_url
          .book_image
            = image_tag article.image_url
        .article_details
          .article_title
            = article.title
          .booktitle
            = article.book_title
          .author_name
            = article.author
          .article_toppage_content
            = article.content[0,50]
      .article_toppage_heart
        = image_tag 'heart.svg', class: 'iine-image'
        %span= article.likes.count

app/views/searchs/index.html.haml
- if user_signed_in?
  検索
  = form_tag(books_path,:method => 'get') do
    = text_field_tag :search
    = submit_tag 'Search', :name => nil
- else
  = link_to 'ログインして記事を書く', new_user_session_path, class: 'text-decoration'
  

app/views/timelines/index.html.haml
= render 'commons/articles', articles: @articles